# Generated by Django 4.2.13 on 2024-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
