# Generated by Django 4.2.13 on 2024-05-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-created_on', 'creator']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
