# Generated by Django 4.2.13 on 2024-05-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_rename_featured_image_character_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='image',
            new_name='featured_image',
        ),
    ]
