# Generated by Django 4.2.13 on 2024-05-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_rename_featured_image_character_character_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='content',
            new_name='description',
        ),
    ]
