# Generated by Django 4.2.13 on 2024-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_rename_content_character_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('1', 'Dwarf'), ('2', 'Elf'), ('3', 'Half-Elf'), ('4', 'Human'), ('5', 'Halfling'), ('6', 'Gnome'), ('7', 'Half-Orc'), ('8', 'Dragonborn'), ('9', 'Tiefling'), ('10', 'Githyanki')], default='Human', max_length=50),
        ),
    ]
