# Generated by Django 4.2.13 on 2024-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_character_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='class_archetype',
            field=models.CharField(choices=[('a', 'Barbarian'), ('b', 'Bard'), ('c', 'Cleric'), ('d', 'Druid'), ('e', 'Fighter'), ('f', 'Monk'), ('g', 'Paladin'), ('h', 'Ranger'), ('i', 'Rogue'), ('j', 'Sorcerer'), ('k', 'Warlock'), ('l', 'Wizard')], default='Fighter', max_length=50),
        ),
    ]
