# Generated by Django 4.2.13 on 2024-05-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0011_character_class_archetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.CharField(default='', max_length=100),
        ),
    ]
