# Generated by Django 4.2.13 on 2024-05-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0012_character_armor_character_gender_character_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_archetype',
            field=models.CharField(choices=[('a', 'Barbarian'), ('b', 'Bard'), ('c', 'Cleric'), ('d', 'Druid'), ('e', 'Fighter'), ('f', 'Monk'), ('g', 'Paladin'), ('h', 'Ranger'), ('i', 'Rogue'), ('j', 'Sorcerer'), ('Warlock', 'Warlock'), ('l', 'Wizard')], default='Fighter', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('F', 'Female'), ('N', 'None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Dwarf', 'Dwarf'), ('2', 'Elf'), ('3', 'Half-Elf'), ('4', 'Human'), ('5', 'Halfling'), ('6', 'Gnome'), ('7', 'Half-Orc'), ('8', 'Dragonborn'), ('9', 'Tiefling'), ('10', 'Githyanki')], default='Human', max_length=50),
        ),
    ]
