# Generated by Django 4.2.13 on 2024-05-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0014_alter_character_class_archetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('No Gender', 'No Gender')], default='No Gender', max_length=50),
        ),
    ]
